stages:
  - update
  - build
  - release
  - container

variables:
  GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: none
  NAME: 
    value: ""
    description: "Package name to update and build"
  VERSION:
    value: ""
    description: "Version of the package"

update::version:
  stage: update
  image: local
  rules:
  - if: $CI_PIPELINE_SOURCE == "api"
  tags:
    - nix
  script:
    - if [ -f "${NAME}"/default.nix ]; then export CURR_VERSION=$(cat ./${NAME}/default.nix|awk -F'"' '/version =/ {print $2;} ') ; fi
    - |
      echo "New version : ${VERSION}"
      if [ "${CURR_VERSION}" == "${VERSION}" ]
      then
        echo "Version matched doing nothing"
      else
        echo "Version mismatch updating..."
        if [ -f "${NAME}/update.sh" ]
        then 
          ./${NAME}/update.sh || true
        else
          sed -i "s/version = \"${CURR_VERSION}/version = \"${VERSION}/g" ${NAME}/default.nix
        fi
      fi
  artifacts:
    paths:
      - ${NAME}/
    expire_in: '600'

build::package:
  stage: build
  image: local
  rules:
  - if: $CI_PIPELINE_SOURCE == "api"
  dependencies:
  - update::version
  tags: 
    - nix
  script: 
    - nix-build -A ${NAME}

release::package:
  stage: release
  image: local
  dependencies:
  - update::version
  rules:
  - if: $CI_PIPELINE_SOURCE == "api"
  tags:
    - nix
  script:
    - git config --global user.email "abott@mcth.fr"
    - git config --global user.name "Abott"
    - git config --global "http.${CI_SERVER_URL}.sslCAInfo" "$CI_SERVER_TLS_CA_FILE"
    - git add ${NAME} 
    - git commit -m "Releasing new version for ${NAME} from $CI_COMMIT_SHORT_SHA [skip ci]" || echo "No changes, nothing to commit!"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.mcth.fr/thomas/nix.git
    - git push gitlab_origin HEAD:main
    - git clone https://oauth2:$ACCESS_TOKEN@gitlab.mcth.fr/docker/${NAME}.git docker-${NAME}
    - cd docker-${NAME}
    - |
      if [ $(git rev-parse ${VERSION} >/dev/null 2>&1) ]
      then 
        git tag -a ${VERSION} -m "Update to version ${VERSION} from $CI_COMMIT_SHORT_SHA"
        git push origin ${VERSION}
      else
        echo "Tag already exist"
      fi


      #build::docker:
      #  stage: container
      #  image: local
      #  dependencies:
      #    - release::package
      #  tags:
      #    - nix
      #  rules:
      #    - if: $CI_PIPELINE_SOURCE == "api"
      #    - exists:
      #      - ${NAME}/docker.nix
      #  script:
      #    - nix-shell --run ./build.sh
