name: Building nix packages
run-name: ${{ github.actor }} is running Github actions
on: 
  workflow_call:
    inputs:
      package:
        description: Package name
        required: false
        default: sonarr
        type: string
  push:
jobs:
  Testing:
    runs-on: nixos/nix
    steps:
      - run: echo "Running for package ${inputs.package}"
      - run: nix build .#${inputs.package}
