name: Building nix packages
run-name: ${{ github.actor }} is running Github actions
on: [push]
inputs:
  package:
    description: Package name
    required: false
    default: sonarr
jobs:
  Testing:
    runs-on: nixos/nix
    steps:
      - run: echo "Running for package ${inputs.package}"
      - run: nix build .#${inputs.package}
