name: Building nix packages
run-name: Building a nix package 
on: [push]
jobs:
  Testing:
    runs-on: nixos-nix
    steps:
      - run: echo "Running for package sonarr"
      - run: nix build .#sonarr
