name: Building nix packages
run-name: Building a nix package 
on: [push]
jobs:
  Testing:
    runs-on: native 
    steps:
      - run: echo "Running for package sonarr"
      - run: /run/current-system/sw/bin/nix build .#sonarr
