name: Building nix packages
run-name: Building a nix package 
on: [push]
env:
  PATH: "${PATH}:/run/current-system/sw/bin"
jobs:
  Testing:
    runs-on: native 
    steps:
      - run: echo "Running for package sonarr"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: '5'
      - run: echo "$GITHUB_SHA"
      - run: |
          pwd
          git status
          echo "${GITHUB_SHA}"
          git show --name-only ${GITHUB_SHA}
          git diff-tree --no-commit-id --name-only "${GITHUB_SHA}" 
          
      #- run: nix build .#sonarr 
