name: Building nix packages
run-name: Building a nix package 
on: [push]
env:
  PATH: "${PATH}:/run/current-system/sw/bin"
jobs:
  Testing:
    runs-on: native 
    steps:
      - run: echo "Running for package sonarr"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: whoami
      #- run: /run/current-system/sw/bin/nix-build . -A sonarr 
